before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
after_success:
- "/bin/bash ./scripts/send.sh success $DISCORD_WEBHOOK"
after_failure:
- "/bin/bash ./scripts/send.sh failure $DISCORD_WEBHOOK"
notifications:
  email: false
sudo: required
language: go
go:
- '1.10'
services:
- docker
jobs:
  include:
  - stage: build
    script:
    - make lint
    - make test
    - make build
deploy:
  skip_cleanup: true
  provider: script
  script: make deploy
  on:
    branch: master
