before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
after_success:
- "/bin/bash ./scripts/send.sh success $DISCORD_WEBHOOK"
after_failure:
- "/bin/bash ./scripts/send.sh failure $DISCORD_WEBHOOK"
notifications:
  email: false
sudo: required
language: go
go:
- '1.10'
services:
- docker
jobs:
  include:
  - stage: build
    script:
    - make lint
    - make test
    - make build
deploy:
  skip_cleanup: true
  provider: script
  script: make deploy
  on:
    branch: master
env:
  global:
  - secure: AA97je2SfIT9Wk6v0Rd/SWdJQpulKgwUb08zBzBmty8He8prRtDR+RGZvd1Y8F3mkSCsGjmAYJyaIVfTacSWbmc1ulP0FVe3vGDgatJ5OwKUaRa9ZbqHBZ0Kb2XBphnysNolzz7XT4dH7JDKCbizCvmvJSFMtW89TaUixNcfUHwMD6p/DMhlbjVgWQwgNFG4cCSy+QlIb+nTaX1RF2JIFkl+00pBa2Gu5mSyMWAUzH3L55WymtJXIqaxau3b/tapE3YgzlbIYYKCmR5g6kExFchdeZ3nPBaWBwcbMfDa0mNS37mpkqgqeMydCf0+0Qyo/SgCkjzOTeqWSWXzwarKAPdg7OhfPrPXlBrirbReDGaVxzxbF0YIJzalpg00uRqU9/Ahm17jlCKo2/HqfkLtgKpNQgW1LxPLIQ+TQf1duzdLY+13PxeyxEp+YXaLs+OfLY+9cpwfdpQ7oAKs6M3nafh6H+1RggeqsQs3l/O77UCCMTSKvqVKp0kMXgk8QlPApxB7zEQRMhPLsHlqPDqTcOG/Dmj/RfTWIgBw0rGl7FIyz9iBN5S3/edfIa7KrSwHsNSs9Q8IbzuLoiFo/DfaJA59lXsxa6mEM3Mxy8ZitDCOGYXh+NtgZyuNPRK9WJ8Cx0vsbiGy91VKxgN154VCxvskF0lRq0HJHc0jvPxzVhM=
  - secure: lnrCvQDY+HbcHbQfI6uTS9f0iH946zUUH7tl349IwNaw8EnxmwVHjbIiXc1VHWRshQmBGw+mw6MqgljNjgqzSW70tCCd59li2ZfJ4Lxqc9WiIdxjr9hmCI+IcFTdLGsH5nzEy1nBtWMgu0Ebo3A94Bss8Zg4q1xiNotQWL3dYuXCjYNVggONfkg9EUnW2Ow3oZPckb/UQGsShX05bo8bKFgSH5OJgarTESOrsWovfAI6uc8k2nLjix+vV3quOjQ5Yff35oA6vG0BUTq9xR/NwuHA383ywA5NG2OZj2t6FgbfmxfzlPLtoPXOfIdtQfRb4vDfl7lHEMr+SnBb2nieaOTlgQC1pcB2kdX1miSiXSkKGKFRfBCoCgugiVkzPINm04E8DBewj9WAfD5xNG0IPkRdoGXnp70PPSQSe2K9tLPjAfxT+OfUeIg4ZAPr/0DRlp37LiImLdQHXfy8XdCBjSlDlLfx+JHagHVUsy0Jr+aAOTbXKPbJkIIh1znZbJnBG+0LqQ6m4wygRxf8OoeZRy1F3DpAaYyIn21hkm+HoUjSCQdIo+QkMAvSW/klc/FblEXQPFJkqcXfdSGTWxb87gjPmLkgaszhqS11srsDW7yUwgN3vBOXFMP8eqclCi4KPFjlU6ub1zfshM9Ce/Yqf0aXOLDF7+xwLC7U5mf7VVA=
  - secure: vfSw5IxDVAotavGxMblyQNr32kYNVVphEf4xW+tgwcW1Kt1RNB8bFtRmxC8ZAs38TDdh/icci4KGX1DwnKW5iYKGNhwJGZIe26vhtsPUDT+XaJijbHkAEsdEjKKSJAM29OXBDVmy5E6qtlJOxIwWiXxhsJibY5HY5jdL7h0QdESj8WAcgvHqWUtGQmIJSG496L3r+Bng9062hdoIcoKvBk3DXY6vo+g/7hCyBkjtbAvkzIk1gpwbDvLlU2OTdDF73cR2JdsRr9vfr/l0IIqns5LJL8bDG+7jGw21F8LMOwHmi69DED8FLjkIzdyk30PoDHsl7jiUB8VthMfXbS0bGr1lukzqPx7d9xNJzeR/fKSklYakUZPbs0IVqZ8Mv9Slz27WMy27MFGlKGS4++Id2wzpSDXVUrMOA4ozM5KQNf6Mw5FYDfLj+uXsf3DZzrrGlOym2ZBsPJRJA3/H6EJv14cZkv5OaAfwS3qc2sJDYTd22cMX4m4dB5Hhxn8sJW+CWQQmhqreX4sHMRrHiUQqQVz7ukuShLycDrQQtmhwqdR1QKdetifBldg9e+olp8RTAZzNG0DCgKwfaeTNL1OXwqxZobrdfhEZYzMNWTsXzvmj3nNbmqQUaZqHP7lFmhl7jEPJTViwnfRiM8muIKSRly/Z/WJ74R2qLfGioR2/XwY=
