// Code generated by protoc-gen-go. DO NOT EDIT.
// source: outbound.proto

package outbound

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SendChannelMessageInput struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendChannelMessageInput) Reset()         { *m = SendChannelMessageInput{} }
func (m *SendChannelMessageInput) String() string { return proto.CompactTextString(m) }
func (*SendChannelMessageInput) ProtoMessage()    {}
func (*SendChannelMessageInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_outbound_a211e5b5892e01dc, []int{0}
}
func (m *SendChannelMessageInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendChannelMessageInput.Unmarshal(m, b)
}
func (m *SendChannelMessageInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendChannelMessageInput.Marshal(b, m, deterministic)
}
func (dst *SendChannelMessageInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendChannelMessageInput.Merge(dst, src)
}
func (m *SendChannelMessageInput) XXX_Size() int {
	return xxx_messageInfo_SendChannelMessageInput.Size(m)
}
func (m *SendChannelMessageInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SendChannelMessageInput.DiscardUnknown(m)
}

var xxx_messageInfo_SendChannelMessageInput proto.InternalMessageInfo

func (m *SendChannelMessageInput) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *SendChannelMessageInput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendChannelTriviaInput struct {
	TriviaID             string   `protobuf:"bytes,1,opt,name=TriviaID,proto3" json:"TriviaID,omitempty"`
	ChannelID            string   `protobuf:"bytes,2,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	RequestingUserID     string   `protobuf:"bytes,3,opt,name=RequestingUserID,proto3" json:"RequestingUserID,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=Category,proto3" json:"Category,omitempty"`
	Difficulty           string   `protobuf:"bytes,5,opt,name=Difficulty,proto3" json:"Difficulty,omitempty"`
	Choices              []string `protobuf:"bytes,6,rep,name=Choices,proto3" json:"Choices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendChannelTriviaInput) Reset()         { *m = SendChannelTriviaInput{} }
func (m *SendChannelTriviaInput) String() string { return proto.CompactTextString(m) }
func (*SendChannelTriviaInput) ProtoMessage()    {}
func (*SendChannelTriviaInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_outbound_a211e5b5892e01dc, []int{1}
}
func (m *SendChannelTriviaInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendChannelTriviaInput.Unmarshal(m, b)
}
func (m *SendChannelTriviaInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendChannelTriviaInput.Marshal(b, m, deterministic)
}
func (dst *SendChannelTriviaInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendChannelTriviaInput.Merge(dst, src)
}
func (m *SendChannelTriviaInput) XXX_Size() int {
	return xxx_messageInfo_SendChannelTriviaInput.Size(m)
}
func (m *SendChannelTriviaInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SendChannelTriviaInput.DiscardUnknown(m)
}

var xxx_messageInfo_SendChannelTriviaInput proto.InternalMessageInfo

func (m *SendChannelTriviaInput) GetTriviaID() string {
	if m != nil {
		return m.TriviaID
	}
	return ""
}

func (m *SendChannelTriviaInput) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *SendChannelTriviaInput) GetRequestingUserID() string {
	if m != nil {
		return m.RequestingUserID
	}
	return ""
}

func (m *SendChannelTriviaInput) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *SendChannelTriviaInput) GetDifficulty() string {
	if m != nil {
		return m.Difficulty
	}
	return ""
}

func (m *SendChannelTriviaInput) GetChoices() []string {
	if m != nil {
		return m.Choices
	}
	return nil
}

type SendChannelTriviaAnswerInput struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	RequestingUserID     string   `protobuf:"bytes,2,opt,name=RequestingUserID,proto3" json:"RequestingUserID,omitempty"`
	CorrectAnswer        string   `protobuf:"bytes,3,opt,name=CorrectAnswer,proto3" json:"CorrectAnswer,omitempty"`
	UserAnswer           string   `protobuf:"bytes,4,opt,name=UserAnswer,proto3" json:"UserAnswer,omitempty"`
	Timeout              bool     `protobuf:"varint,5,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendChannelTriviaAnswerInput) Reset()         { *m = SendChannelTriviaAnswerInput{} }
func (m *SendChannelTriviaAnswerInput) String() string { return proto.CompactTextString(m) }
func (*SendChannelTriviaAnswerInput) ProtoMessage()    {}
func (*SendChannelTriviaAnswerInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_outbound_a211e5b5892e01dc, []int{2}
}
func (m *SendChannelTriviaAnswerInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendChannelTriviaAnswerInput.Unmarshal(m, b)
}
func (m *SendChannelTriviaAnswerInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendChannelTriviaAnswerInput.Marshal(b, m, deterministic)
}
func (dst *SendChannelTriviaAnswerInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendChannelTriviaAnswerInput.Merge(dst, src)
}
func (m *SendChannelTriviaAnswerInput) XXX_Size() int {
	return xxx_messageInfo_SendChannelTriviaAnswerInput.Size(m)
}
func (m *SendChannelTriviaAnswerInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SendChannelTriviaAnswerInput.DiscardUnknown(m)
}

var xxx_messageInfo_SendChannelTriviaAnswerInput proto.InternalMessageInfo

func (m *SendChannelTriviaAnswerInput) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *SendChannelTriviaAnswerInput) GetRequestingUserID() string {
	if m != nil {
		return m.RequestingUserID
	}
	return ""
}

func (m *SendChannelTriviaAnswerInput) GetCorrectAnswer() string {
	if m != nil {
		return m.CorrectAnswer
	}
	return ""
}

func (m *SendChannelTriviaAnswerInput) GetUserAnswer() string {
	if m != nil {
		return m.UserAnswer
	}
	return ""
}

func (m *SendChannelTriviaAnswerInput) GetTimeout() bool {
	if m != nil {
		return m.Timeout
	}
	return false
}

func init() {
	proto.RegisterType((*SendChannelMessageInput)(nil), "outbound.SendChannelMessageInput")
	proto.RegisterType((*SendChannelTriviaInput)(nil), "outbound.SendChannelTriviaInput")
	proto.RegisterType((*SendChannelTriviaAnswerInput)(nil), "outbound.SendChannelTriviaAnswerInput")
}

func init() { proto.RegisterFile("outbound.proto", fileDescriptor_outbound_a211e5b5892e01dc) }

var fileDescriptor_outbound_a211e5b5892e01dc = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x86, 0xd3, 0x72, 0x2f, 0xb7, 0x9c, 0xe4, 0x1a, 0x9d, 0x05, 0x4e, 0x90, 0x18, 0x24, 0xc6,
	0x18, 0x17, 0x25, 0xd1, 0x27, 0xd0, 0xe2, 0x82, 0x05, 0x21, 0x22, 0x2e, 0x74, 0x57, 0xe0, 0x50,
	0x26, 0x81, 0x19, 0x9c, 0xce, 0x68, 0x78, 0x00, 0xdf, 0xcd, 0x07, 0xf0, 0x81, 0xcc, 0xb4, 0x53,
	0x2c, 0x96, 0x1a, 0x97, 0xff, 0x3f, 0x27, 0xff, 0xc9, 0x77, 0xfa, 0x17, 0xf6, 0x84, 0x56, 0x63,
	0xa1, 0xf9, 0xd4, 0x5f, 0x49, 0xa1, 0x04, 0xf1, 0x32, 0xdd, 0x38, 0x8a, 0x84, 0x88, 0x16, 0xd8,
	0x49, 0xfc, 0xb1, 0x9e, 0x75, 0x70, 0xb9, 0x52, 0xeb, 0x74, 0xac, 0x7d, 0x07, 0x87, 0xf7, 0xc8,
	0xa7, 0xc1, 0x3c, 0xe4, 0x1c, 0x17, 0x7d, 0x8c, 0xe3, 0x30, 0xc2, 0x1e, 0x5f, 0x69, 0x45, 0x9a,
	0x50, 0xb3, 0x76, 0xaf, 0x4b, 0x9d, 0x96, 0x73, 0x5e, 0x1b, 0x7e, 0x19, 0x84, 0xc2, 0x3f, 0x3b,
	0x4d, 0xdd, 0xe4, 0x2d, 0x93, 0xed, 0x0f, 0x07, 0xea, 0xb9, 0xcc, 0x91, 0x64, 0x2f, 0x2c, 0x4c,
	0x23, 0x1b, 0xe0, 0x59, 0x99, 0x25, 0x6e, 0xf4, 0xf6, 0x3a, 0xf7, 0xfb, 0xba, 0x0b, 0xd8, 0x1f,
	0xe2, 0xb3, 0xc6, 0x58, 0x31, 0x1e, 0x3d, 0xc4, 0x28, 0x7b, 0x5d, 0x5a, 0x49, 0x86, 0x0a, 0xbe,
	0xd9, 0x12, 0x84, 0x0a, 0x23, 0x21, 0xd7, 0xf4, 0x4f, 0xba, 0x25, 0xd3, 0xe4, 0x18, 0xa0, 0xcb,
	0x66, 0x33, 0x36, 0xd1, 0x0b, 0xb5, 0xa6, 0x7f, 0x93, 0xd7, 0x9c, 0x63, 0xb0, 0x82, 0xb9, 0x60,
	0x13, 0x8c, 0x69, 0xb5, 0x55, 0x31, 0x58, 0x56, 0xb6, 0xdf, 0x1d, 0x68, 0x16, 0xb0, 0xae, 0x79,
	0xfc, 0x8a, 0xf2, 0x37, 0xf7, 0xda, 0x05, 0xe0, 0x96, 0x00, 0x9c, 0xc2, 0xff, 0x40, 0x48, 0x89,
	0x13, 0x95, 0xe6, 0x5b, 0xd2, 0x6d, 0xd3, 0xa0, 0x98, 0x79, 0x3b, 0x92, 0x82, 0xe6, 0x1c, 0x83,
	0x32, 0x62, 0x4b, 0x14, 0x5a, 0x25, 0x9c, 0xde, 0x30, 0x93, 0x97, 0x6f, 0x2e, 0x78, 0x03, 0x5b,
	0x0f, 0x32, 0x00, 0x52, 0x6c, 0x00, 0x39, 0xf1, 0x37, 0x7d, 0x2a, 0xe9, 0x47, 0xa3, 0xee, 0xa7,
	0xc5, 0xf2, 0xb3, 0x62, 0xf9, 0xb7, 0xa6, 0x58, 0xa4, 0x0f, 0x07, 0x85, 0x3b, 0x91, 0xd6, 0xce,
	0xbc, 0x5c, 0x37, 0x4a, 0xe3, 0x1e, 0xb7, 0x1a, 0x9a, 0x3f, 0x3b, 0x39, 0xfb, 0x21, 0x34, 0xf7,
	0x65, 0xca, 0xa2, 0x6f, 0xe0, 0x69, 0xf3, 0x97, 0x8c, 0xab, 0xc9, 0xdb, 0xd5, 0x67, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x7b, 0xdf, 0xa7, 0x1c, 0x48, 0x03, 0x00, 0x00,
}
